#page title
page_title                                :  Dropcode - Sharing Files by QR Code                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
test_flight_id                            : 

appstore_link                             : http://dropcode-123513.herokuapp.com/                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Dropcode                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Sharing Files by QR Code                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Dropcode allows you to easily share files on your iPhone with any computer running a web browser.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Luca Beurer-Kellner                                
your_link                                 : 
your_city                                 : Zurich
email_address                             : lucabeurerkellner@gmail.com
facebook_username                         : 
instagram_username                        : 
twitter_username                          : lbeurerkellner
github_username                           : lbeurerkellner
youtube_username                          :

# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : No Setup
    description                           : Choose a file on your phone, visit the Dropcode website on a computer and scan the QR code. That's how quickly you can share your files in a copy shop, with a hotel computer or anyone else.
    fontawesome_icon_name                 : fighter-jet

  - title                                 : No Login
    description                           : Using Dropcode, you no longer need to log into your cloud storage or email account on an untrusted computer, just to access a file.
    fontawesome_icon_name                 : lock

  - title                                 : No Tracking
    description                           : Dropcode does not save your files when transferring them from your phone and a computer.
    fontawesome_icon_name                 : eye


# Theme Settings
topbar_color                              : "#47A88A"
topbar_transparency                       : 0.7
topbar_title_color                        : "#ffffff"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
